stages:
  - build
  - push
  - deploy

variables:
  # Configuration de ton registre Docker
  REGISTRY: "10.2.0.106:5001"
  IMAGE_NAME: "harvester"
  TAG: "latest"

# Étape de build
build:
  stage: build
  script:
    - docker build -t $REGISTRY/$IMAGE_NAME:$TAG .

# Étape de push (pousser l'image vers le registre Docker)
push:
  stage: push
  script:
    - docker push $REGISTRY/$IMAGE_NAME:$TAG
  only:
    - main  # Pousser l'image uniquement si on est sur la branche 'main' (ou 'master')

# Étape de déploiement (optionnel, selon ton besoin)
deploy:
  stage: deploy
  script:
    - echo "Déploiement de l'image sur le serveur ou dans un environnement de staging..."
    - ssh julien@10.2.0.106 'docker pull $REGISTRY/$IMAGE_NAME:$TAG && docker run -d --name $IMAGE_NAME $REGISTRY/$IMAGE_NAME:$TAG'
  only:
    - main
