stages:
  - build
  - push
  - deploy

# Étape de build
build:
  stage: build
  script:
    - docker build -t $REGISTRY/$IMAGE_NAME:$TAG .

# Étape de push (pousser l'image vers le registre Docker)
push:
  stage: push
  script:
    - docker push $REGISTRY/$IMAGE_NAME:$TAG
  only:
    - main  # Pousser l'image uniquement si on est sur la branche 'main' (ou 'master')

# Étape de déploiement via SSH
deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache openssh  # ou apt-get install si tu es sur Debian
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Déploiement de l'image Docker sur le serveur distant"
    - ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "docker pull $REGISTRY/$IMAGE_NAME:$TAG && docker stop harvester || true && docker rm harvester || true && docker run -d --name harvester $REGISTRY/$IMAGE_NAME:$TAG"
  only:
    - main

