stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_TAG: "$(git describe --tags $(git rev-list --tags --max-count=1))-$(git rev-parse --short HEAD)"

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG .

test:
  stage: test
  script:
    - docker run --rm $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG pytest

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
